/**
 * In-app legal content (Privacy + Terms), rendered natively in DeskCare style
 * so the user NEVER leaves the app to an external site (tester 2026-06-02).
 * Source text mirrored from oqapps.pro/legal, rebranded DeskFit -> DeskCare.
 * Regenerate: see scripts (fetch + extract) — do not hand-edit block-by-block.
 */
export type LegalBlock = { k: "title" | "h" | "p" | "li"; t: string };

export const PRIVACY_BLOCKS: LegalBlock[] = [
  { k: "title", t: `Privacy Policy — DeskCare` },
  { k: "h", t: `1. Introduction` },
  { k: "p", t: `This Privacy Policy explains how OQapps ("we", "us", or "our") collects, uses, and protects your personal information when you use the DeskCare mobile application ("the App"). DeskCare is a wellness application for office and remote workers. It provides 2-5 minute video exercises targeting neck, back, eyes, and wrists, along with specialized programs (e.g., for sciatica or carpal tunnel relief), smart reminders, and pain tracking.` },
  { k: "p", t: `By downloading, installing, or using the App, you agree to the collection and use of information in accordance with this Policy. If you do not agree, please do not use the App.` },
  { k: "h", t: `2. Information We Collect` },
  { k: "p", t: `We collect the following categories of information:` },
  { k: "li", t: `Account information: email address, name, and (optionally) profile picture.` },
  { k: "li", t: `Device information: device model, operating system version, advertising identifiers (IDFA on iOS, AAID on Android), language, and region.` },
  { k: "li", t: `Usage data: screens viewed, features used, session length, and interactions with notifications.` },
  { k: "li", t: `Health-related information: fitness and wellness-related information you choose to log (such as symptoms, mood, sleep schedule, or dietary intake). This data is treated as sensitive and stored securely.` },
  { k: "li", t: `Subscription and purchase information: subscription status, transaction identifiers, and renewal dates. We do not receive your full payment card details — Apple and Google process payments directly.` },
  { k: "li", t: `Communications: messages you send to our support team.` },
  { k: "li", t: `Crash and diagnostic data: automatically collected when the app crashes, to help us fix bugs.` },
  { k: "h", t: `3. How We Use Your Information` },
  { k: "p", t: `We use the information we collect for the following purposes:` },
  { k: "li", t: `To provide and operate the App — including authentication, syncing your data across devices, and delivering core features. (Legal basis under GDPR: performance of contract.)` },
  { k: "li", t: `To improve and develop the App — analyzing how features are used so we can fix bugs, optimize performance, and build better products. (Legal basis: legitimate interest.)` },
  { k: "li", t: `To provide customer support — responding to your questions and resolving issues. (Legal basis: performance of contract.)` },
  { k: "li", t: `To send service-related communications — such as account confirmation, security alerts, and important updates. (Legal basis: legitimate interest / legal obligation.)` },
  { k: "li", t: `To send marketing communications — only if you have opted in. You can unsubscribe at any time. (Legal basis: consent.)` },
  { k: "li", t: `To comply with legal obligations — such as tax, accounting, or law-enforcement requests. (Legal basis: legal obligation.)` },
  { k: "h", t: `4. Third-Party Service Providers` },
  { k: "p", t: `We use the following third-party services to operate the App. Each provider has its own privacy policy, which governs how they handle your data:` },
  { k: "p", t: `We share with each provider only the minimum information needed to perform their function. We do not sell your personal information to data brokers.` },
  { k: "h", t: `5. Data Sharing and Disclosure` },
  { k: "p", t: `Beyond the third-party service providers listed above, we may share your information in the following limited circumstances:` },
  { k: "li", t: `Legal requirements: if required by law, court order, or governmental authority.` },
  { k: "li", t: `Business transfers: in connection with a merger, acquisition, or sale of assets, in which case the acquiring party will be bound by this Policy.` },
  { k: "li", t: `With your consent: for any other purpose you explicitly approve.` },
  { k: "p", t: `We do not sell, rent, or trade your personal information.` },
  { k: "h", t: `6. Data Retention` },
  { k: "p", t: `We retain your personal information for as long as your account is active or as needed to provide the App. After account deletion, we delete or anonymize your data within 30 days, except where retention is required by law (e.g., financial records, which we retain for up to seven years).` },
  { k: "p", t: `Anonymized analytics that cannot identify you may be retained indefinitely.` },
  { k: "h", t: `7. Your Rights and Choices` },
  { k: "h", t: `If you are in the European Economic Area, the United Kingdom, or Switzerland (GDPR)` },
  { k: "p", t: `You have the following rights:` },
  { k: "li", t: `Right of access — request a copy of the personal information we hold about you.` },
  { k: "li", t: `Right to rectification — correct inaccurate information.` },
  { k: "li", t: `Right to erasure ("right to be forgotten") — request deletion of your personal information.` },
  { k: "li", t: `Right to restriction of processing.` },
  { k: "li", t: `Right to data portability — receive your data in a portable format.` },
  { k: "li", t: `Right to object to processing based on legitimate interest.` },
  { k: "li", t: `Right to withdraw consent at any time, where processing is based on consent.` },
  { k: "li", t: `Right to lodge a complaint with your local data protection authority.` },
  { k: "h", t: `If you are a California resident (CCPA / CPRA)` },
  { k: "p", t: `You have the right to:` },
  { k: "li", t: `Know what personal information we collect, use, disclose, and sell or share.` },
  { k: "li", t: `Delete personal information we have collected about you.` },
  { k: "li", t: `Correct inaccurate personal information.` },
  { k: "li", t: `Opt out of the sale or sharing of your personal information (we do not sell or share for cross-context behavioral advertising).` },
  { k: "li", t: `Limit use of sensitive personal information.` },
  { k: "li", t: `Non-discrimination for exercising your rights.` },
  { k: "p", t: `To exercise any of these rights, contact privacy@oqapps.pro . We will respond within 30 days (45 days under CCPA, with one possible extension).` },
  { k: "h", t: `For all users` },
  { k: "p", t: `You can delete your account at any time. See our Account Deletion page for instructions.` },
  { k: "h", t: `8. International Data Transfers` },
  { k: "p", t: `Your information may be processed in the United States or other countries where our service providers operate. When we transfer personal data from the EEA, UK, or Switzerland to a country that has not received an adequacy decision, we use Standard Contractual Clauses (SCCs) approved by the European Commission to safeguard the transfer.` },
  { k: "h", t: `9. Security` },
  { k: "p", t: `We use industry-standard measures to protect your information, including encryption in transit (TLS) and at rest, access controls, and regular security audits. However, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.` },
  { k: "p", t: `If we become aware of a breach affecting your personal information, we will notify you and the relevant authorities as required by applicable law.` },
  { k: "h", t: `10. Children's Privacy` },
  { k: "p", t: `The App is not directed to children under the age of 13. We do not knowingly collect personal information from children under 13 (or under 16 in the European Economic Area). If you believe a child has provided us with personal information, please contact privacy@oqapps.pro and we will delete it promptly.` },
  { k: "h", t: `11. Changes to This Policy` },
  { k: "p", t: `We may update this Privacy Policy from time to time. Material changes will be communicated through the App, by email, or through a prominent notice on our website at least 30 days before they take effect. Continued use of the App after changes take effect constitutes acceptance of the updated Policy.` },
  { k: "h", t: `12. Contact Us` },
  { k: "p", t: `If you have questions or concerns about this Privacy Policy or our data practices, contact us:` },
  { k: "li", t: `Privacy email: privacy@oqapps.pro` },
  { k: "li", t: `General support: support@oqapps.pro` },
  { k: "li", t: `Website: https://oqapps.pro` },
  { k: "h", t: `13. Fitness and Wellness Information` },
  { k: "p", t: `DeskCare processes wellness and fitness information you log (such as pain points, exercises completed, and reminders). We do not sell, share, or use this information for advertising. You can delete this data at any time by contacting privacy@oqapps.pro .` },
  { k: "p", t: `Document version: v1.0 · Effective: May 08, 2026 · Last updated: May 08, 2026` },
  { k: "p", t: `If you have questions about this document, contact us at legal@oqapps.pro .` },
];

export const TERMS_BLOCKS: LegalBlock[] = [
  { k: "title", t: `Terms of Service — DeskCare` },
  { k: "p", t: `These Terms of Service ("Terms") govern your use of the DeskCare mobile application ("the App"), provided by OQapps ("we", "us", or "our"). By installing, accessing, or using the App, you agree to these Terms. If you do not agree, do not use the App.` },
  { k: "li", t: `Acceptance of Terms` },
  { k: "li", t: `License` },
  { k: "li", t: `Eligibility` },
  { k: "li", t: `Account` },
  { k: "li", t: `Acceptable Use` },
  { k: "li", t: `User Content` },
  { k: "li", t: `Subscriptions and Billing` },
  { k: "li", t: `Fitness and Wellness Disclaimer` },
  { k: "li", t: `Intellectual Property` },
  { k: "li", t: `Termination` },
  { k: "li", t: `Disclaimers` },
  { k: "li", t: `Limitation of Liability` },
  { k: "li", t: `Indemnification` },
  { k: "li", t: `Governing Law` },
  { k: "li", t: `Dispute Resolution` },
  { k: "li", t: `Apple-Specific Terms` },
  { k: "li", t: `Changes to These Terms` },
  { k: "li", t: `General` },
  { k: "li", t: `Contact` },
  { k: "h", t: `1. Acceptance of Terms` },
  { k: "p", t: `By downloading, installing, or using the App, you agree to be bound by these Terms and our Privacy Policy . If you are using the App on behalf of an organization, you represent that you have the authority to bind that organization.` },
  { k: "h", t: `2. License` },
  { k: "p", t: `Subject to your compliance with these Terms, OQapps grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to install and use the App on devices you own or control, solely for your personal, non-commercial use.` },
  { k: "p", t: `This license does not grant you any right to: (a) modify, adapt, translate, reverse engineer, decompile, or disassemble the App; (b) remove or alter any proprietary notices; (c) use the App for any commercial purpose without our prior written consent; or (d) transfer the App to anyone else.` },
  { k: "h", t: `3. Eligibility` },
  { k: "p", t: `You must be at least 13 years old to use the App. If you are a minor in your jurisdiction, you must have permission from a parent or legal guardian. By using the App, you represent that you meet these requirements.` },
  { k: "h", t: `4. Account` },
  { k: "p", t: `To access certain features, you must create an account. You agree to: (a) provide accurate and complete information; (b) keep your password and credentials secure; (c) be responsible for all activity under your account; and (d) notify us immediately of any unauthorized access. We may suspend or terminate accounts that violate these Terms or that we reasonably suspect of fraudulent activity.` },
  { k: "h", t: `5. Acceptable Use` },
  { k: "p", t: `You agree not to:` },
  { k: "li", t: `Use the App for any illegal, harmful, or fraudulent purpose.` },
  { k: "li", t: `Harass, threaten, defame, or abuse any other person.` },
  { k: "li", t: `Attempt to gain unauthorized access to the App, our systems, or other users' accounts.` },
  { k: "li", t: `Reverse engineer, decompile, or extract source code from the App.` },
  { k: "li", t: `Use bots, scrapers, or automated tools to access the App.` },
  { k: "li", t: `Submit content that infringes intellectual property or privacy rights.` },
  { k: "li", t: `Interfere with the operation of the App, including denial-of-service attacks.` },
  { k: "li", t: `Resell or commercialize access to the App without our written consent.` },
  { k: "h", t: `6. User Content` },
  { k: "p", t: `You retain ownership of any content you submit to the App ("User Content"). By submitting User Content, you grant OQapps a worldwide, non-exclusive, royalty-free, sublicensable license to host, store, reproduce, modify (for technical purposes only), and display your User Content solely for the purpose of providing and improving the App.` },
  { k: "p", t: `You represent and warrant that: (a) you own or have the necessary rights to your User Content; (b) your User Content does not violate any law or third-party right; and (c) you are responsible for the accuracy of your User Content.` },
  { k: "p", t: `We reserve the right (but not the obligation) to review, remove, or refuse any User Content that we believe violates these Terms or applicable law.` },
  { k: "h", t: `7. Subscriptions and Billing` },
  { k: "p", t: `DeskCare offers auto-renewable subscriptions. The following terms apply:` },
  { k: "li", t: `Length and price: the subscription length and price are displayed in the App before purchase, and confirmed by Apple App Store or Google Play before charging your account.` },
  { k: "li", t: `Auto-renewal: your subscription will automatically renew at the end of each subscription period unless you cancel at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period.` },
  { k: "li", t: `Free trials: if a free trial is offered, it converts to a paid subscription at the end of the trial unless you cancel before the trial ends. Unused portions of a free trial are forfeited if you purchase a subscription.` },
  { k: "li", t: `How to cancel: you can manage and cancel subscriptions through your Apple ID account settings (iOS) or Google Play account settings (Android). Deleting the App does not cancel your subscription.` },
  { k: "li", t: `Refunds: all payments are processed by Apple or Google. Refund requests must be made through Apple App Store or Google Play directly. We do not process refunds outside their systems.` },
  { k: "li", t: `Price changes: if we change subscription prices, we will notify you in advance. Continued use after the change takes effect constitutes acceptance.` },
  { k: "h", t: `9. Fitness and Wellness Disclaimer` },
  { k: "p", t: `The exercises and recommendations in DeskCare are for general wellness purposes and are not personalized medical advice. Before starting any exercise program — especially if you have an existing condition or injury — consult a qualified healthcare professional. Stop immediately and seek medical advice if you experience pain, dizziness, or discomfort. You assume all risk associated with using the App's exercise content.` },
  { k: "h", t: `10. Intellectual Property` },
  { k: "p", t: `The App, including its design, code, content, branding, trademarks, and AI models, is owned by OQapps and protected by copyright, trademark, and other intellectual property laws. Except for the limited license granted in Section 2, no rights are transferred to you.` },
  { k: "p", t: `"OQapps", "DeskCare", and related logos are trademarks of OQapps. You may not use them without our prior written consent.` },
  { k: "h", t: `11. Termination` },
  { k: "p", t: `You may stop using the App at any time and delete your account through the App or by contacting support@oqapps.pro . We may suspend or terminate your access to the App at any time, with or without notice, for any violation of these Terms or for legal or business reasons. Upon termination, your right to use the App ceases immediately. Sections that by their nature should survive (Intellectual Property, Disclaimers, Limitation of Liability, Indemnification, Governing Law, Dispute Resolution) will survive.` },
  { k: "h", t: `12. Disclaimers` },
  { k: "p", t: `THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS.` },
  { k: "p", t: `SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES. IN SUCH JURISDICTIONS, OUR LIABILITY IS LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.` },
  { k: "h", t: `13. Limitation of Liability` },
  { k: "p", t: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, OQAPPS AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AND AGENTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR USE, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR THE APP.` },
  { k: "p", t: `OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE APP WILL NOT EXCEED THE GREATER OF (A) USD 100 OR (B) THE AMOUNTS YOU PAID TO US IN THE TWELVE (12) MONTHS PRIOR TO THE CLAIM.` },
  { k: "h", t: `14. Indemnification` },
  { k: "p", t: `You agree to indemnify, defend, and hold harmless OQapps and its affiliates from any claims, damages, losses, and expenses (including reasonable attorneys' fees) arising out of: (a) your violation of these Terms; (b) your User Content; (c) your violation of any law or third-party right; or (d) your misuse of the App.` },
  { k: "h", t: `15. Governing Law` },
  { k: "p", t: `These Terms are governed by and construed in accordance with the laws of England and Wales , without regard to conflict-of-law principles.` },
  { k: "h", t: `16. Dispute Resolution` },
  { k: "p", t: `Any dispute, controversy, or claim arising out of or in connection with these Terms — including their existence, validity, interpretation, performance, breach, or termination — will be referred to and finally resolved by arbitration under the LCIA Arbitration Rules , which are deemed to be incorporated by reference into this clause. The seat of arbitration will be London, England. The language of the arbitration will be English. The number of arbitrators will be one.` },
  { k: "p", t: `Class action waiver. You and OQapps each agree that disputes will be resolved on an individual basis only and not as part of any class, consolidated, or representative action.` },
  { k: "p", t: `Notwithstanding the above, either party may seek injunctive or equitable relief in any court of competent jurisdiction to protect intellectual property rights.` },
  { k: "h", t: `17. Apple-Specific Terms` },
  { k: "p", t: `If you downloaded the App from the Apple App Store, the following additional terms apply:` },
  { k: "li", t: `These Terms are concluded between you and OQapps only, and not with Apple. OQapps, not Apple, is solely responsible for the App and its content.` },
  { k: "li", t: `Apple has no obligation to furnish maintenance and support services with respect to the App.` },
  { k: "li", t: `In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever.` },
  { k: "li", t: `OQapps, not Apple, is responsible for addressing any claims by you or any third party relating to the App, including product-liability claims, claims that the App fails to conform to any applicable legal or regulatory requirement, and claims arising under consumer-protection or similar legislation.` },
  { k: "li", t: `OQapps, not Apple, is responsible for the investigation, defense, settlement, and discharge of any third-party intellectual-property infringement claim relating to the App.` },
  { k: "li", t: `You represent that you are not located in a country that is subject to a US Government embargo, or that has been designated by the US Government as a "terrorist supporting" country, and that you are not listed on any US Government list of prohibited or restricted parties.` },
  { k: "li", t: `Apple and Apple's subsidiaries are third-party beneficiaries of these Terms. Upon your acceptance, Apple has the right (and is deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary.` },
  { k: "h", t: `18. Changes to These Terms` },
  { k: "p", t: `We may update these Terms from time to time. Material changes will be communicated through the App or by email at least 30 days before they take effect. Continued use of the App after changes take effect constitutes acceptance.` },
  { k: "h", t: `19. General` },
  { k: "li", t: `Severability: if any provision is held invalid, the remaining provisions remain in effect.` },
  { k: "li", t: `No waiver: our failure to enforce any right or provision is not a waiver of that right or provision.` },
  { k: "li", t: `Assignment: you may not assign these Terms without our consent. We may assign these Terms in connection with a merger, acquisition, or sale of assets.` },
  { k: "li", t: `Entire agreement: these Terms, together with the Privacy Policy , constitute the entire agreement between you and OQapps regarding the App and supersede all prior agreements.` },
  { k: "li", t: `Force majeure: we are not liable for delays or failures due to causes beyond our reasonable control.` },
  { k: "h", t: `20. Contact` },
  { k: "p", t: `Questions about these Terms? Contact us:` },
  { k: "li", t: `Legal email: legal@oqapps.pro` },
  { k: "li", t: `General support: support@oqapps.pro` },
  { k: "li", t: `Website: https://oqapps.pro` },
  { k: "p", t: `Document version: v1.0 · Effective: May 08, 2026 · Last updated: May 08, 2026` },
  { k: "p", t: `If you have questions about this document, contact us at legal@oqapps.pro .` },
];
